version: '3.2'
services:
  crew-app:
    container_name: crew-app 
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "crew-app:latest"
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://crew-app:5000/
  
  integration_tests:
    container_name: integration_tests
    image: "cypress/included:3.2.0"
    depends_on: 
      - crew-app
    entrypoint: yarn run cypress open; cypress run
    environment:
      - CYPRESS_baseUrl=http://crew-app:5000/
    working_dir: /e2e
    volumes:
      - ./:/e2e